[build]
  command = "echo 'default context'"
[context.production]
  command = "ls -lha"
[context.deploy-preview]
[context.deploy-preview.environment]
  ACCESS_TOKEN = "not so secret"
[context.branch-deploy]
  command = "echo branch"
[context.branch-deploy.environment]
  NODE_ENV = "development"
[context.staging] # 'staging' is a branch name
  command = "echo 'staging'"
  base = "staging"
[context."feat/branch"]
  command = "echo 'special branch'"
  base = "branch"

[[redirects]]
  from = "/*"
  to = "/blog/:splat"

[[redirects]]
  from = "/404.html"
  to = "/index.html"
  status = 302
  force = true
  [redirects.headers]
    X-From = "Netlify"
    X-Api-Key = "some-api-key-string"

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    HiThere = "fromNetply"
